### ISSUE TITLE
Passwort zurücksetzen

### ISSUE THREAD

**Issue by Wunst** [Wunst/mPSdigital#14]
### User Story
Als Lehrer kann ich das Passwort meiner Schüler zurücksetzen.
Als Admin kann ich das Passwort aller Personen zurücksetzen.

### Tasks
- "Passwort zurücksetzen"-API (Backend)
- Admin-Panel (Frontend) vmtl. bei der "Hinzufügen"-Seite

**Comment by Wunst** [comment]
@deinadmin Die API existiert

**Comment by deinadmin** [comment]
Erledigt!
![CleanShot 2024-02-09 at 12 17 42@2x](https://github.com/Wunst/mPSdigital/assets/53299224/482c56f7-a9b6-403b-9ea7-32166e75de56)
